# ▼ 重複回避：coc.nvimを使うなら deoplete は外す or 完全遅延＋手動トグル
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# on_event = 'InsertEnter'
# hook_add = '''
#   let g:deoplete#enable_at_startup = 0
# '''

[[plugins]]
repo = 'neoclide/coc.nvim'
source = 'release'
# coc は通常読み込み推奨（初期化遅延で不具合が出やすい）
hook_add = '''
  let g:coc_global_extensions = [
    \ 'coc-rust-analyzer',
    \ 'coc-tsserver',
    \ 'coc-json',
    \ 'coc-prettier',
    \ ]
'''
# build は release なら通常不要。必要なら:
# build = 'coc#util#install()'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
  nnoremap <leader>f :FZF<CR>
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tpope/vim-surround'        # 軽量：常時読み込みでもOK

# コメント系はどれか1つに
[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]] # Svelte.js
repo = 'evanleck/vim-svelte'

[[plugins]]
repo = 'czheo/mojo.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
